// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeqhnG4K1Q6y7_ndLJnqcm9uFY16JB8Vg',
    appId: '1:824019089088:web:af266cdd07acd0dff61f25',
    messagingSenderId: '824019089088',
    projectId: 'dailyreminderapp-974fe',
    authDomain: 'dailyreminderapp-974fe.firebaseapp.com',
    storageBucket: 'dailyreminderapp-974fe.firebasestorage.app',
    measurementId: 'G-4YCM6DMW9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWEPjv5MvIT_-23teCeBtvW_urO-isM_4',
    appId: '1:824019089088:android:204611e683d8007ff61f25',
    messagingSenderId: '824019089088',
    projectId: 'dailyreminderapp-974fe',
    storageBucket: 'dailyreminderapp-974fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDta1WO-R9WPyZbKnhofanzk4PCCGN5i6U',
    appId: '1:824019089088:ios:b1f19e90b853e4e8f61f25',
    messagingSenderId: '824019089088',
    projectId: 'dailyreminderapp-974fe',
    storageBucket: 'dailyreminderapp-974fe.firebasestorage.app',
    iosBundleId: 'com.example.dailyReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDta1WO-R9WPyZbKnhofanzk4PCCGN5i6U',
    appId: '1:824019089088:ios:b1f19e90b853e4e8f61f25',
    messagingSenderId: '824019089088',
    projectId: 'dailyreminderapp-974fe',
    storageBucket: 'dailyreminderapp-974fe.firebasestorage.app',
    iosBundleId: 'com.example.dailyReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeqhnG4K1Q6y7_ndLJnqcm9uFY16JB8Vg',
    appId: '1:824019089088:web:329ad4e3fcc3801cf61f25',
    messagingSenderId: '824019089088',
    projectId: 'dailyreminderapp-974fe',
    authDomain: 'dailyreminderapp-974fe.firebaseapp.com',
    storageBucket: 'dailyreminderapp-974fe.firebasestorage.app',
    measurementId: 'G-VYNENR6SYB',
  );
}
